/// Conformance against `tools/protocol/golden.json`.
///
/// The golden file is generated by `tools/protocol/generate-golden.mjs` from
/// `tools/protocol/codec.js`, and `docs/02-ble-protocol.md` §10 states that all
/// three implementations (firmware C++, Dart, JavaScript) are cross-checked
/// against it. This is the Dart half of that promise.
///
/// **The frame bytes are authoritative; the JSON alongside them is not.** Two
/// expectations in the shipped golden file are stale, and this test asserts the
/// bytes rather than the metadata:
///
/// * `telemetryImpact.telemetry.flags` is `255`, but the frame carries `0xF7`
///   (247) — every named §5.1 bit except `SOS_BUTTON`.
/// * `telemetrySaturated.telemetry.ay` is `-32767`, but the frame carries
///   `0x8000` = `-32768`, which is the correct i16 minimum and is exactly what
///   `clampI16(-40000)` produces.
///
/// Both are documented in the library header of
/// `lib/data/protocol/ble_frame.dart`. If a future regeneration fixes them, the
/// [golden metadata is self-consistent] test will start passing on its own.
///
/// The file is read at runtime rather than inlined, so the vectors cannot drift
/// out of sync with the repository. If it is missing (the `app/` package
/// extracted on its own) every test in this file skips instead of failing.
library;

import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:flutter_test/flutter_test.dart';
import 'package:smart_accident_alert/data/protocol/ble_frame.dart';
import 'package:smart_accident_alert/data/protocol/telemetry.dart';
import 'package:smart_accident_alert/domain/entities/telemetry.dart';

/// Path to the golden vectors, relative to the `app/` package root.
const String kGoldenRelativePath = '../tools/protocol/golden.json';

final File? _goldenFile = _locateGolden();

File? _locateGolden() {
  for (final String candidate in <String>[
    kGoldenRelativePath,
    'tools/protocol/golden.json',
    '../tools/protocol/golden.json',
  ]) {
    final File file = File(candidate);
    if (file.existsSync()) {
      return file;
    }
  }
  return null;
}

Map<String, Object?>? _goldenJson() {
  final File? file = _goldenFile;
  if (file == null) {
    return null;
  }
  final Object? decoded = jsonDecode(file.readAsStringSync());
  return decoded is Map<String, Object?> ? decoded : null;
}

Uint8List _hexBytes(Object? hex) {
  final String clean = (hex! as String).replaceAll(' ', '');
  final Uint8List out = Uint8List(clean.length ~/ 2);
  for (int i = 0; i < out.length; i++) {
    out[i] = int.parse(clean.substring(i * 2, i * 2 + 2), radix: 16);
  }
  return out;
}

List<Map<String, Object?>> _vectors() {
  final Map<String, Object?>? json = _goldenJson();
  if (json == null) {
    return <Map<String, Object?>>[];
  }
  final Object? raw = json['vectors'];
  if (raw is! List<Object?>) {
    return <Map<String, Object?>>[];
  }
  return raw.whereType<Map<String, Object?>>().toList();
}

/// Decode [payload] or fail with the codec's own message.
TelemetryRecord _mustDecode(Uint8List payload) {
  final TelemetryRecord? record = TelemetryCodec.tryDecode(payload);
  if (record == null) {
    throw StateError(
      'expected a ${payload.length}-byte telemetry record, '
      'wanted $telemetryRecordBytes',
    );
  }
  return record;
}

String? get _skipReason => _goldenFile == null
    ? 'tools/protocol/golden.json not found; run from the repository root'
    : null;

void main() {
  final List<Map<String, Object?>> vectors = _vectors();
  final String? skip = _skipReason;

  test(
    'golden.json was located and parsed',
    () {
      expect(
        skip,
        isNull,
        reason: 'the conformance suite is meaningless without the vectors',
      );
      expect(vectors, isNotEmpty);
    },
    skip: skip,
  );

  group('every golden vector decodes to a CRC-verified frame', () {
    for (final Map<String, Object?> vector in vectors) {
      final String name = vector['name']! as String;
      test(
        name,
        () {
          final Uint8List raw = _hexBytes(vector['frameHex']);
          final FrameScanner scanner = FrameScanner();
          final List<BleFrame> frames = scanner.scanToList(raw);

          expect(frames, hasLength(1), reason: '$name: frame count');
          final BleFrame frame = frames.single;

          expect(frame.typeCode, vector['type'], reason: '$name: TYPE');
          expect(frame.version, kProtocolVersion, reason: '$name: VER');
          expect(frame.frameLength, raw.length, reason: '$name: total length');

          // LEN is self-describing: 6 + LEN + 2 must equal the frame length.
          expect(
            frame.payload.length,
            raw.length - kHeaderBytes - kCrcBytes,
            reason: '$name: LEN',
          );

          // LEN is 0…512 for every vector in the file.
          expect(frame.payload.length, lessThanOrEqualTo(kMaxPayloadBytes));

          expect(scanner.stats.crcErrors, 0, reason: '$name: CRC');
          expect(scanner.stats.discardedBytes, 0, reason: '$name: noise');
        },
        skip: skip,
      );
    }
  });

  group('every golden vector survives arbitrary fragmentation', () {
    for (final Map<String, Object?> vector in vectors) {
      final String name = vector['name']! as String;
      test(
        name,
        () {
          final Uint8List raw = _hexBytes(vector['frameHex']);
          final FrameScanner whole = FrameScanner();
          final List<BleFrame> expected = whole.scanToList(raw);
          expect(expected, hasLength(1));

          // Deterministic split points covering "split inside the header",
          // "split inside the payload" and "split inside the CRC".
          for (final int cut in <int>{
            1,
            2,
            kHeaderBytes - 1,
            kHeaderBytes,
            kHeaderBytes + 1,
            raw.length ~/ 2,
            raw.length - 1,
          }) {
            if (cut <= 0 || cut >= raw.length) {
              continue;
            }
            final FrameScanner scanner = FrameScanner();
            final List<BleFrame> frames = <BleFrame>[];
            scanner.scan(Uint8List.sublistView(raw, 0, cut), (BleFrameView v) {
              frames.add(v.copy());
              return true;
            });
            scanner.scan(Uint8List.sublistView(raw, cut), (BleFrameView v) {
              frames.add(v.copy());
              return true;
            });
            expect(frames, hasLength(1), reason: '$name split at $cut');
            expect(
              frames.single.payload,
              expected.single.payload,
              reason: '$name split at $cut: payload differs',
            );
          }
        },
        skip: skip,
      );
    }
  });

  group('telemetry vectors', () {
    for (final Map<String, Object?> vector in vectors) {
      if (vector['type'] != MessageType.telemetry.code) {
        continue;
      }
      final String name = vector['name']! as String;
      test(
        name,
        () {
          final Uint8List raw = _hexBytes(vector['frameHex']);
          final FrameScanner scanner = FrameScanner();
          final List<TelemetryRecord> records = <TelemetryRecord>[];
          scanner.scan(raw, (BleFrameView view) {
            final TelemetryRecord? record = TelemetryCodec.decodeFrame(view);
            if (record != null) {
              records.add(record);
            }
            return true;
          });

          expect(records, hasLength(1), reason: name);
          final TelemetryRecord record = records.single;
          final Map<String, Object?> reference =
              vector['telemetry']! as Map<String, Object?>;

          // Fields the golden metadata gets right. The two stale fields are
          // asserted separately, from the bytes.
          void expectField(String key, int actual) {
            expect(actual, reference[key], reason: '$name.$key');
          }

          expectField('tMs', record.tMs);
          expectField('ax', record.accX);
          expectField('az', record.accZ);
          expectField('magMg', record.magMg);
          expectField('peakMg', record.peakMg);
          expectField('score', record.impactScore);
          expectField('batteryPct', record.batteryPct);
          expectField('state', record.state.byte);

          // Round-trip: the encoder must reproduce the exact 18 bytes.
          expect(
            TelemetryCodec.encode(record).toList(),
            record.toBytes().toList(),
          );
          final Uint8List reencoded = encodeFrame(
            typeCode: MessageType.telemetry.code,
            payload: TelemetryCodec.encode(record),
          );
          expect(reencoded.toList(), raw.toList(), reason: '$name: re-encode');
        },
        skip: skip,
      );
    }
  });

  group('manifest and wire agree (regressions)', () {
    // The generator once recorded `flags: 0xFF` for a frame whose only clear
    // bit is LED_GREEN, and recorded `-32767` for a value that saturates to the
    // int16 minimum. Both were fixed in `generate-golden.mjs`, so the manifest
    // can no longer disagree with its own wire image. These are the assertions
    // that keep it that way.

    test('telemetryImpact sets every flag except LED_GREEN', () {
      final Map<String, Object?> vector = vectors.firstWhere(
        (Map<String, Object?> v) => v['name'] == 'telemetryImpact',
      );
      final Map<String, Object?> telemetry =
          vector['telemetry']! as Map<String, Object?>;

      final FrameScanner scanner = FrameScanner();
      final List<BleFrame> frames =
          scanner.scanToList(_hexBytes(vector['frameHex']));
      final TelemetryRecord record = _mustDecode(frames.single.payload);

      // The manifest must state what the wire actually carries.
      expect(record.flags.toByte(), telemetry['flags']);
      expect(record.flags.toByte(), 0xF7);
      expect(record.flags.sw420, isTrue);
      expect(record.flags.buzzer, isTrue);
      expect(record.flags.ledRed, isTrue);
      expect(record.flags.oledOk, isTrue);
      expect(record.flags.sosButton, isTrue);
      expect(record.flags.armed, isTrue);
      expect(record.flags.charging, isTrue);
      expect(record.flags.ledGreen, isFalse, reason: 'the one clear bit');
    });

    test('telemetrySaturated saturates to the int16 bounds', () {
      final Map<String, Object?> vector = vectors.firstWhere(
        (Map<String, Object?> v) => v['name'] == 'telemetrySaturated',
      );
      final Map<String, Object?> telemetry =
          vector['telemetry']! as Map<String, Object?>;

      final FrameScanner scanner = FrameScanner();
      final List<BleFrame> frames =
          scanner.scanToList(_hexBytes(vector['frameHex']));
      final TelemetryRecord record = _mustDecode(frames.single.payload);

      // Clamp, not two's-complement wraparound: -99999 must land on the minimum.
      expect(record.accY, -32768);
      expect(record.accY, telemetry['ay']);
      expect(record.accX, 32767);
      expect(record.magMg, 65535);
      expect(record.batteryPct, kBatteryUnknown);
      expect(record.hasBattery, isFalse);
    });

    test(
      'maxPayload is 403 bytes, and the spec text says 512',
      () {
        final Map<String, Object?> vector = vectors
            .firstWhere((Map<String, Object?> v) => v['name'] == 'maxPayload');
        final FrameScanner scanner = FrameScanner();
        final List<BleFrame> frames =
            scanner.scanToList(_hexBytes(vector['frameHex']));
        expect(frames.single.payload, hasLength(403));
        // The description calls it "CALIB_LOG at MAX_PAYLOAD (512 B)"; the frame
        // is 411 bytes = 6 + 403 + 2. The generator pads the sample list to its
        // own budget, not to kMaxPayloadBytes.
        expect(frames.single.frameLength, 411);
      },
      skip: skip,
    );

    test(
      'CALIB_LOG is an object with a samples array, not a bare array',
      () {
        final Map<String, Object?> vector = vectors
            .firstWhere((Map<String, Object?> v) => v['name'] == 'maxPayload');
        final FrameScanner scanner = FrameScanner();
        final List<BleFrame> frames =
            scanner.scanToList(_hexBytes(vector['frameHex']));
        final Map<String, Object?>? json = frames.single.jsonPayload;
        expect(json, isNotNull);
        expect(json!.containsKey('samples'), isTrue);
        expect(json['samples'], isA<List<Object?>>());
      },
      skip: skip,
    );
  });

  group('golden metadata is self-consistent', () {
    test(
      'every JSON vector round-trips through the Dart encoder',
      () {
        for (final Map<String, Object?> vector in vectors) {
          final Object? json = vector['json'];
          if (json == null) {
            continue;
          }
          final String name = vector['name']! as String;
          final Map<String, Object?> payload = json as Map<String, Object?>;
          final Uint8List encoded = encodeJsonFrame(
            typeCode: vector['type']! as int,
            json: payload,
          );
          final FrameScanner scanner = FrameScanner();
          final List<BleFrame> frames = scanner.scanToList(encoded);
          expect(frames, hasLength(1), reason: name);
          expect(
            frames.single.jsonPayload,
            payload,
            reason: '$name: JSON payload must survive encode -> decode',
          );
        }
      },
      skip: skip,
    );

    test(
      'the documented frame for a JSON vector is what our encoder produces',
      () {
        // golden.json records both the payload JSON and the full frame. The
        // reference encoder emits keys in *insertion* order, not sorted, so
        // `encodeJson`'s default must reproduce `frameHex` byte for byte. This is
        // the assertion that catches a whitespace or key-order change in
        // `encodeJson`, which nothing else in the suite would notice.
        //
        // §6 claims keys are "sorted for stable diffing"; the reference does not
        // do that, and neither do we by default. See `encodeJson`.
        for (final Map<String, Object?> vector in vectors) {
          final Object? json = vector['json'];
          if (json == null) {
            continue;
          }
          final String name = vector['name']! as String;
          final Map<String, Object?> payload = json as Map<String, Object?>;
          final Uint8List ours = encodeJsonFrame(
            typeCode: vector['type']! as int,
            json: payload,
          );
          final Uint8List theirs = _hexBytes(vector['frameHex']);
          expect(ours, hasLength(theirs.length), reason: '$name: frame length');
          expect(ours.toList(), theirs.toList(), reason: '$name: frame bytes');
        }
      },
      skip: skip,
    );

    test(
      'sorting keys changes the bytes but not the decoded value',
      () {
        // Documents that `sortKeys: true` is a real, opt-in behaviour change, so
        // nobody enables it and then reports a "protocol regression" that is
        // really a key-order diff.
        const Map<String, Object?> payload = <String, Object?>{
          'type': 'ACCIDENT_DETECTED',
          'eventId': '8f3a1c22',
          'seq': 7,
        };
        final String insertion = encodeJson(payload);
        final String sorted = encodeJson(payload, sortKeys: true);
        expect(
          insertion,
          '{"type":"ACCIDENT_DETECTED","eventId":"8f3a1c22","seq":7}',
        );
        expect(
          sorted,
          '{"eventId":"8f3a1c22","seq":7,"type":"ACCIDENT_DETECTED"}',
        );
        expect(
          decodeJsonObject(Uint8List.fromList(utf8.encode(insertion))),
          payload,
        );
        expect(
          decodeJsonObject(Uint8List.fromList(utf8.encode(sorted))),
          payload,
        );
      },
      skip: skip,
    );
  });

  group('constants', () {
    test(
      'SOF, version and telemetry size match the frozen spec',
      () {
        final Map<String, Object?>? json = _goldenJson();
        final Map<String, Object?> constants =
            json!['constants']! as Map<String, Object?>;
        expect(constants['SOF0'], kSof0);
        expect(constants['SOF1'], kSof1);
        expect(constants['TELEMETRY_SIZE'], telemetryRecordBytes);
        expect(constants['MAX_PAYLOAD'], kMaxPayloadBytes);
        expect(json['protocolVersion'], kProtocolVersion);
      },
      skip: skip,
    );

    test(
      'every §4 message type code matches the golden constants',
      () {
        final Map<String, Object?>? json = _goldenJson();
        final Map<String, Object?> constants =
            json!['constants']! as Map<String, Object?>;
        final Map<String, Object?> types =
            constants['Type']! as Map<String, Object?>;
        // `Type` is keyed by name in the generator; assert the codes we depend on.
        const Map<String, int> expected = <String, int>{
          'HELLO': 0x01,
          'PING': 0x02,
          'CONFIG': 0x04,
          'CALIBRATE': 0x05,
          'COMMAND': 0x06,
          'ACK': 0x07,
          'ERROR': 0x08,
          'EVENT': 0x09,
          'TELEMETRY': 0x10,
          'STATUS': 0x11,
          'HELLO_ACK': 0x12,
          'CALIB_LOG': 0x13,
          'DIAG': 0x14,
          'DEVICE_INFO': 0x20,
        };
        expected.forEach((String name, int code) {
          expect(MessageType.fromCode(code), isNotNull, reason: name);
          expect(types[name], code, reason: name);
        });
      },
      skip: skip,
    );

    test(
      'the Dart type codes equal the frozen table in §4',
      () {
        // Guards against an enum entry being renumbered.
        expect(MessageType.hello.code, 0x01);
        expect(MessageType.ping.code, 0x02);
        expect(MessageType.config.code, 0x04);
        expect(MessageType.calibrate.code, 0x05);
        expect(MessageType.command.code, 0x06);
        expect(MessageType.ack.code, 0x07);
        expect(MessageType.error.code, 0x08);
        expect(MessageType.event.code, 0x09);
        expect(MessageType.telemetry.code, 0x10);
        expect(MessageType.status.code, 0x11);
        expect(MessageType.helloAck.code, 0x12);
        expect(MessageType.calibLog.code, 0x13);
        expect(MessageType.diag.code, 0x14);
        expect(MessageType.deviceInfo.code, 0x20);
        expect(MessageType.fromCode(0x03), isNull, reason: '§4 skips 0x03');
      },
      skip: skip,
    );
  });
}
